[project]
name = "tiara-starlumos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "databases>=0.9.0",
    "nb-cli>=1.7.4",
    "nonebot-adapter-bilibili>=0.0.7",
    "nonebot-adapter-bilibili-live>=0.2.6",
    "nonebot-adapter-console>=0.10.0",
    "nonebot-adapter-satori>=1.3.0",
    "nonebot-adapter-wxclaw>=0.2.1",
    "nonebot-plugin-alconna>=0.62.1",
    "nonebot-plugin-localstore>=0.7.4",
    "nonebot-plugin-orm[postgresql]>=0.8.3",
    "nonebot-plugin-permission>=0.3.1",
    "nonebot2[fastapi,httpx,quart,websockets]>=2.5.0",
    "pytz>=2026.3.post1",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
test = [
    "anyio>=4.14.2",
    "nonebug>=0.4.4",
]

[[tool.uv.index]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[tool.nonebot]
plugin_dirs = ["Tiara_bot/plugins"]
builtin_plugins = []

[tool.nonebot.plugins]
"@local" = []
nonebot-plugin-orm = ["nonebot_plugin_orm"]
nonebot-plugin-localstore = ["nonebot_plugin_localstore"]

[tool.nonebot.adapters]
"@local" = []
