"""first revision

迁移 ID: 448a48981ed3
父迁移: 
创建时间: 2026-09-14 17:34:36.626116

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '448a48981ed3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('sign',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
