"""empty message

迁移 ID: c79ff3277179
父迁移: 
创建时间: 2026-09-21 16:44:07.765935

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c79ff3277179'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='QQ群号'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='群名称'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_group')),
    info={'bind_key': 'user_data'}
    )
    with op.batch_alter_table('bot_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_group_group_id'), ['group_id'], unique=True)

    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='QQ号'),
    sa.Column('nickname', sa.String(length=128), nullable=False, comment='最后记录的昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='权限级别: user, admin, owner'),
    sa.Column('is_banned', sa.Boolean(), nullable=False, comment='是否被封禁'),
    sa.Column('level', sa.Integer(), nullable=False, comment='等级'),
    sa.Column('exp', sa.Integer(), nullable=False, comment='经验值'),
    sa.Column('coins', sa.Integer(), nullable=False, comment='金币/通用货币'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='首次交互时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_user')),
    info={'bind_key': 'user_data'}
    )
    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_user_user_id'), ['user_id'], unique=True)

    op.create_table('bot_user_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname_in_group', sa.String(length=128), nullable=True, comment='群昵称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否还在本群(退群后置为False)'),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='首次加群时间'),
    sa.Column('left_at', sa.DateTime(), nullable=True, comment='退群时间'),
    sa.ForeignKeyConstraint(['group_id'], ['bot_group.group_id'], name=op.f('fk_bot_user_group_group_id_bot_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['bot_user.user_id'], name=op.f('fk_bot_user_group_user_id_bot_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_user_group')),
    sa.UniqueConstraint('user_id', 'group_id', name='uix_user_group'),
    info={'bind_key': 'user_data'}
    )
    with op.batch_alter_table('bot_user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_user_group_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_user_group_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_user_group_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_user_group_group_id'))

    op.drop_table('bot_user_group')
    with op.batch_alter_table('bot_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_user_user_id'))

    op.drop_table('bot_user')
    with op.batch_alter_table('bot_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_group_group_id'))

    op.drop_table('bot_group')
    # ### end Alembic commands ###
